import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.css"
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Navbar } from "./_component/Navbar/Navbar";
import Footer from "./_component/Footer/Footer";
import { Toaster } from "@/components/ui/sonner"

const Encode_Sansfont = Encode_Sans({
 weight:["100","400","800"],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ Encode_Sansfont.className} `}
      >
        <Navbar/>
        <main className="p-5">
          {children}
        </main>
        <Toaster/>
        <Footer/>

      </body>
    </html>
  );
}
